spring:
  application:
    name: spirng-boot-rabbitmq
  rabbitmq:
    ####连接地址
    host: 127.0.0.1
    ####端口号   
    port: 5672
    ####账号 
    username: guest
    ####密码  
    password: guest
    ### 地址
    virtual-host: /springboot-host
    listener:
      simple:
        ####开启手动ack  
        #acknowledge-mode: manual 
        retry:
          ####开启消费者（程序出现异常的情况下会）进行重试
          enabled: true
          ####最大重试次数（5次之后还未消费成功，放弃消息）
          max-attempts: 5
          ####重试间隔次数
          initial-interval: 3000
             

server:
  port: 8080